#GUI file generated by GUI Pie, developed by Jabberwock
#https://apps.microsoft.com/store/detail/gui-pie/9P5TH15LZSL7


import os
import sys
import subprocess
import math
from tkinter import *
from tkinter import ttk
import tkinter.font
try:
  from PIL import ImageTk, Image, ImageOps
except:
  print('Installing PIL.')
  subprocess.check_call(['pip', 'install', 'pillow'])
  print('Done.')
  from PIL import ImageTk, Image, ImageOps

if __name__ == "__main__":
  augh = Tk()
else:
  augh = Tk()
augh.title('augh')
dpi = 96
augh.geometry('1920x1080')
augh.grid_propagate(False)
for x in range(32):
  Grid.columnconfigure(augh, x, weight=1, uniform='row')
  Label(augh, width = 1, bg = '#FFE3E1').grid(row = 0, column = x, sticky = N+S+E+W)
for y in range(18):
  Grid.rowconfigure(augh, y, weight=1, uniform='row')
  Label(augh, width = 1, bg = '#FFE3E1').grid(row = y, column = 0, sticky = N+S+E+W)
augh.configure(background='#FFE3E1')

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~WIDGETS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

augh.LandingPageArtOriginal = Image.open('/Assets/Abstruct/')
augh.LandingPageArtImage = ImageOps.exif_transpose(augh.LandingPageArtOriginal)
augh.LandingPageArtImage = ImageTk.PhotoImage(augh.LandingPageArtImage.resize((math.ceil(840 * dpi / 96), math.ceil(840 * dpi / 96)), Image.Resampling.LANCZOS))
augh.LandingPageArt = Label(augh, image = augh.LandingPageArtImage, width = 1, height = 1, bg = '#FFE3E1')
augh.LandingPageArt.grid(row = 2, column = 2, columnspan = 14, rowspan = 14, sticky = N+S+E+W)
augh.INTI_BannerOriginal = Image.open('/Assets/INTI_Banner.png')
augh.INTI_BannerImage = ImageOps.exif_transpose(augh.INTI_BannerOriginal)
augh.INTI_BannerImage = ImageTk.PhotoImage(augh.INTI_BannerImage.resize((math.ceil(359 * dpi / 96), math.ceil(120 * dpi / 96)), Image.Resampling.LANCZOS))


augh.INTI_Banner = Label(augh, image = augh.INTI_BannerImage, width = 1, height = 1, bg = '#FFE3E1')
augh.INTI_Banner.grid(row = 2, column = 20, columnspan = 8, rowspan = 2, sticky = N+S+E+W)


haveanaccountlabel = Label(window, text = "Already have an account?", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', bg = '#00FFFF')
haveanaccountlabel.grid(row = 15, column = 20, columnspan = 5, rowspan = 1, sticky = N+S+E+W)
SignUpLabel = Label(window, text = "Please enter your details as shown.", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', bg = '#FFF5E4')
SignUpLabel.grid(row = 5, column = 20, columnspan = 8, rowspan = 1, sticky = N+S+E+W)
passwordsignupentry = Entry(augh, width = 1, bg = '#FFFFFF', font = ('Arial', 16), justify = 'center')
passwordsignupentry.grid(row = 11, column = 21, columnspan = 6, rowspan = 1, sticky = N+S+E+W)
passwordsignupentry.insert(0, "Please enter your password")
SignUpEmailEntry = Entry(window, width = 1, bg = '#FFFFFF', font = ('Arial', 16), justify = 'center')
SignUpEmailEntry.grid(row = 9, column = 21, columnspan = 6, rowspan = 1, sticky = N+S+E+W)
SignUpEmailEntry.insert(0, "Please enter your student email")
Entry1 = Entry(window, width = 1, bg = '#FFFFFF', font = ('Arial', 16), justify = 'center')
Entry1.grid(row = 7, column = 21, columnspan = 2, rowspan = 1, sticky = N+S+E+W)
Entry1.insert(0, "First Name")
Entry2 = Entry(window, width = 1, bg = '#FFFFFF', font = ('Arial', 16), justify = 'center')
Entry2.grid(row = 7, column = 25, columnspan = 2, rowspan = 1, sticky = N+S+E+W)
Entry2.insert(0, "Last Name")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~BUTTONS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def runregisterbutton(argument):
  if not(__name__ == '__main__'):
    from signuplandingscreen import registerbutton
    try:
      registerbutton(argument)
    except TypeError:
      registerbutton()
def runEvent1(argument):
  if not(__name__ == '__main__'):
    from signuplandingscreen import Event1
    try:
      Event1(argument)
    except TypeError:
      Event1()
signupregister = Button(window, text = "SIGN UP", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', command = lambda: runregisterbutton("signupregister"), bg = '#FFF5E4')
signupregister.grid(row = 13, column = 21, columnspan = 6, rowspan = 1, sticky = N+S+E+W)
gotosigninbutton = Button(window, text = "Click here for sign in page", font = ('Arial', 14), width = 1, height = 1, fg = '#000000', command = lambda: runEvent1("gotosigninbutton"), bg = '#00FFFF')
gotosigninbutton.grid(row = 15, column = 26, columnspan = 2, rowspan = 1, sticky = N+S+E+W)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~HELPER FUNCTIONS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def initModules():
  raise Exception('This main file is outdated. Script signuplandingscreen.py must be updated to reflect the changes in GUI Pie v3.')
def init():
  from signuplandingscreen import registerbutton
  from signuplandingscreen import Event1
augh.initModules = initModules
def hide():
  augh.withdraw()
def show():
  augh.deiconify()
def hideAllWidgets():
    augh.haveanaccountlabel.grid_remove()
    augh.SignUpLabel.grid_remove()
    augh.passwordsignupentry.grid_remove()
    augh.SignUpEmailEntry.grid_remove()
    augh.Entry1.grid_remove()
    augh.Entry2.grid_remove()
    augh.signupregister.grid_remove()
    augh.gotosigninbutton.grid_remove()
    augh.LandingPageArt.grid_remove()
    augh.INTI_Banner.grid_remove()
augh.hideAllWidgets = hideAllWidgets
def showAllWidgets():
    augh.haveanaccountlabel.grid()
    augh.SignUpLabel.grid()
    augh.passwordsignupentry.grid()
    augh.SignUpEmailEntry.grid()
    augh.Entry1.grid()
    augh.Entry2.grid()
    augh.signupregister.grid()
    augh.gotosigninbutton.grid()
    augh.LandingPageArt.grid()
    augh.INTI_Banner.grid()
augh.showAllWidgets = showAllWidgets
def run():
  global dimensions
  dimensions = [0,0]
  if __name__ != "__main__":
    init()
  resizeEvent(None)
  augh.mainloop()
augh.run = run
augh.hide = hide
augh.show = show

dimensions = [augh.winfo_width(), augh.winfo_height()]
def resize():
  global augh, dimensions
  if augh.winfo_width() != dimensions[0] or augh.winfo_height() != dimensions[1]:
    augh.haveanaccountlabel.config(wraplength = math.ceil(augh.winfo_width() * 5 / 32) + 2)
    augh.SignUpLabel.config(wraplength = math.ceil(augh.winfo_width() * 8 / 32) + 2)
    augh.signupregister.config(wraplength = math.ceil(augh.winfo_width() * 6 / 32) + 2)
    augh.gotosigninbutton.config(wraplength = math.ceil(augh.winfo_width() * 2 / 32) + 2)
    augh.LandingPageArtOriginal = Image.open(r'D:/Syncthingstuff/Abstruct/Colored ocean in another world.jpg')
    augh.LandingPageArtImage = ImageOps.exif_transpose(augh.LandingPageArtOriginal)
    if (augh.winfo_height() / 18 * 14) * 2340 / 2340 < augh.winfo_width() * 14 / 32:
      augh.LandingPageArtImage = ImageTk.PhotoImage(augh.LandingPageArtImage.resize((math.ceil(augh.winfo_height() * 14 / 18 * 2340 / 2340), math.ceil(augh.winfo_height() * 14 / 18)), Image.Resampling.LANCZOS))
    else:
      augh.LandingPageArtImage = ImageTk.PhotoImage(augh.LandingPageArtImage.resize((math.ceil(augh.winfo_width() * 14 / 32), math.ceil(augh.winfo_width() * 14 / 32 * 2340 / 2340)), Image.Resampling.LANCZOS))
    augh.LandingPageArt.config(image = augh.LandingPageArtImage)
    augh.INTI_BannerOriginal = Image.open(r'C:/Users/matth/Desktop/yeah/Home-Banner-INTI.png')
    augh.INTI_BannerImage = ImageOps.exif_transpose(augh.INTI_BannerOriginal)
    if (augh.winfo_height() / 18 * 2) * 1201 / 401 < augh.winfo_width() * 8 / 32:
      augh.INTI_BannerImage = ImageTk.PhotoImage(augh.INTI_BannerImage.resize((math.ceil(augh.winfo_height() * 2 / 18 * 1201 / 401), math.ceil(augh.winfo_height() * 2 / 18)), Image.Resampling.LANCZOS))
    else:
      augh.INTI_BannerImage = ImageTk.PhotoImage(augh.INTI_BannerImage.resize((math.ceil(augh.winfo_width() * 8 / 32), math.ceil(augh.winfo_width() * 8 / 32 * 401 / 1201)), Image.Resampling.LANCZOS))
    augh.INTI_Banner.config(image = augh.INTI_BannerImage)
    dimensions = [augh.winfo_width(), augh.winfo_height()]

eventID = None
augh.resizeDelay = 100
def resizeEvent(event):
  global eventID
  if eventID:
    augh.after_cancel(eventID)
  eventID = augh.after(augh.resizeDelay, resize)
augh.bind('<Configure>', resizeEvent)
if __name__ == "__main__":
  augh.run()
